- hosts: all
  become: True
  tasks:
   - name: Install Apache Server
     yum:
       name: httpd
       state: latest
   - name: Start http 
     service:
        name: httpd
        state: started
        enabled: yes
